# Generated by Django 4.2 on 2023-04-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='User Profile',
        ),
    ]
